name: Build

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8 for Build
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Generate settings.xml
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{ "id": "download-from-github-qubitpi", "url": "https://maven.pkg.github.com/qubitpi/athena" }]'
          servers: '[{"id": "download-from-github-qubitpi", "username": "anybody", "password": "${{ secrets.DOWNLOAD_FROM_GITHUB_ARTIFACTORY }}"}]'
      - name: Build
        run: |
          mvn -B clean verify
